[2025-05-10T17:43:31.187+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: titanic_ml_pipeline.train_and_log_model scheduled__2024-12-08T00:00:00+00:00 [queued]>
[2025-05-10T17:43:31.195+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: titanic_ml_pipeline.train_and_log_model scheduled__2024-12-08T00:00:00+00:00 [queued]>
[2025-05-10T17:43:31.196+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-05-10T17:43:31.208+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): train_and_log_model> on 2024-12-08 00:00:00+00:00
[2025-05-10T17:43:31.217+0000] {standard_task_runner.py:60} INFO - Started process 3841 to run task
[2025-05-10T17:43:31.220+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'titanic_ml_pipeline', 'train_and_log_model', 'scheduled__2024-12-08T00:00:00+00:00', '--job-id', '226', '--raw', '--subdir', 'DAGS_FOLDER/***_pipeline.py', '--cfg-path', '/tmp/tmpl2xx95co']
[2025-05-10T17:43:31.221+0000] {standard_task_runner.py:88} INFO - Job 226: Subtask train_and_log_model
[2025-05-10T17:43:31.264+0000] {task_command.py:423} INFO - Running <TaskInstance: titanic_ml_pipeline.train_and_log_model scheduled__2024-12-08T00:00:00+00:00 [running]> on host e821d368632d
[2025-05-10T17:43:31.327+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='titanic_ml_pipeline' AIRFLOW_CTX_TASK_ID='train_and_log_model' AIRFLOW_CTX_EXECUTION_DATE='2024-12-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-08T00:00:00+00:00'
[2025-05-10T17:43:31.392+0000] {logging_mixin.py:188} WARNING - 2025/05/10 17:43:31 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2025-05-10T17:43:31.508+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/mlflow/types/utils.py:407: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details.
  warnings.warn(

[2025-05-10T17:43:33.460+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-05-10T17:43:33.469+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=titanic_ml_pipeline, task_id=train_and_log_model, execution_date=20241208T000000, start_date=20250510T174331, end_date=20250510T174333
[2025-05-10T17:43:33.519+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-05-10T17:43:33.533+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
