[2025-05-10T16:59:05.418+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: titanic_ml_pipeline.preprocess_data scheduled__2023-03-05T00:00:00+00:00 [queued]>
[2025-05-10T16:59:06.952+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: titanic_ml_pipeline.preprocess_data scheduled__2023-03-05T00:00:00+00:00 [queued]>
[2025-05-10T16:59:06.954+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-05-10T16:59:07.023+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): preprocess_data> on 2023-03-05 00:00:00+00:00
[2025-05-10T16:59:07.089+0000] {standard_task_runner.py:60} INFO - Started process 376 to run task
[2025-05-10T16:59:07.143+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'titanic_ml_pipeline', 'preprocess_data', 'scheduled__2023-03-05T00:00:00+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/***_pipeline.py', '--cfg-path', '/tmp/tmp8t_mcmtu']
[2025-05-10T16:59:07.152+0000] {standard_task_runner.py:88} INFO - Job 20: Subtask preprocess_data
[2025-05-10T16:59:07.402+0000] {task_command.py:423} INFO - Running <TaskInstance: titanic_ml_pipeline.preprocess_data scheduled__2023-03-05T00:00:00+00:00 [running]> on host b4499c736a15
[2025-05-10T16:59:07.647+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='titanic_ml_pipeline' AIRFLOW_CTX_TASK_ID='preprocess_data' AIRFLOW_CTX_EXECUTION_DATE='2023-03-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-03-05T00:00:00+00:00'
[2025-05-10T16:59:07.662+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/airflow_pipeline.py", line 29, in load_and_preprocess_data
    df = pd.read_csv('/opt/airflow/data/Titanic.csv', delimiter=',')
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 912, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 577, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1407, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1661, in _make_engine
    self.handles = get_handle(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/common.py", line 859, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/data/Titanic.csv'
[2025-05-10T16:59:07.727+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=titanic_ml_pipeline, task_id=preprocess_data, execution_date=20230305T000000, start_date=20250510T165905, end_date=20250510T165907
[2025-05-10T16:59:07.791+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 20 for task preprocess_data ([Errno 2] No such file or directory: '/opt/airflow/data/Titanic.csv'; 376)
[2025-05-10T16:59:07.848+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-05-10T16:59:07.949+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
